# Generated by Django 2.2.5 on 2020-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=10)),
                ('projectdetail', models.TextField(max_length=1000)),
                ('projectType', models.CharField(choices=[('S', 'SIDE_PROJECT'), ('M', 'MAIN_PROJECT')], max_length=3)),
                ('projectSdate', models.DateField()),
                ('projectEdate', models.DateField()),
            ],
        ),
    ]
